version: '3'
services:
  app:
    build:
      context: ./app
    expose:
      - '9292'
    environment:
      - flag=flag{Luc4s_cann0t_shoot_PK_St4rst0rm}
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
