version: '3'
services:
  app:
    build:
      context: ./app
    expose:
      - '9292'
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
